version: '3.8'

services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend
    ports:
      - "3306:3306"  
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "user", "--password=userpass"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: db
      PMA_USER: user
      PMA_PASSWORD: userpass
    ports:
      - 8089:80
    depends_on:
      - db
    networks:
      - backend

  flyway:
    image: flyway/flyway:latest
    volumes:
      - ./migrations:/flyway/sql
    depends_on:
      db: 
        condition: service_healthy
    command: >
      migrate -url=jdbc:mysql://db:3306/mydb -user=user -password=userpass
    networks:
      - backend
    environment:
      - FLYWAY_BASELINE_ON_MIGRATE=true


  app:  
    build:
      context: .  
      dockerfile: Dockerfile  
    ports:
      - "5000:5000" 
    depends_on:
      - db 
    networks:
      - backend
    environment:
      - DOCKER=1

volumes:
  db-data:

networks:
  backend:
